web:
  build: .
  environment:
    - QV_BASE_URL=https://lcas.lincoln.ac.uk/qv/
#    - QV_BASE_URL=http://10.210.9.146:5000/
  #command: python -u app.py
  ports:
    - "5000:80"
  volumes:
    - .:/quickvote
  links:
    - db
db:
  image: mongo:3.0.2
  volumes:
    - /vol/mongodb:/data/db

express:
  image: mongo-express
  links:
    - db
  environment:
    - ME_CONFIG_MONGODB_SERVER=db
  ports:
    - "8081:8081"
